### ISSUE TITLE
has some errors on the client side

### ISSUE THREAD

**Issue by pepski1270** [BryceCanyonCounty/bcc-legendaries#2]
the script is not running well. prompts and blips had errors
![image](https://user-images.githubusercontent.com/104223970/221271772-88d68183-f272-48a4-a06c-69a8dad641e7.png)
![image](https://user-images.githubusercontent.com/104223970/221271957-0610812b-7270-420e-8bc7-da97c87c6b4b.png)

**Comment by jakeyboi1** [comment]
It is becouse you do not have all the required scripts. You need to have this on your server. https://github.com/VORPCORE/vorp_utils

**Comment by jakeyboi1** [comment]
Download vorp_utils install it then try and let me know if that fixes it
